org.gradle.jvmargs=-Xmx4G -Dfile.encoding=UTF-8
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.warning.mode=all

minecraft_version=26.2
loader_version=0.19.5
fabric_api_version=0.154.2+26.2
java_version=26
java_release=25

mod_version=1.0.0
maven_group=io.github.ran4om.kiaclef
archives_base_name=kiaclef
